[package]
name = "slice2rs"
version = "0.1.0"
authors = ["cemoktra <b.schubert82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ice-rs = { path = "../Ice" }
clap = "3.0.0-beta.2"