[package]
name = "ice-rs"
version = "0.1.0"
authors = ["cemoktra <b.schubert82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
Inflector = "0.11"
pest = "2.0"
pest_derive = "2.0"