proxystring = { SOI ~ ident ~ ":" ~ endpoint ~ EOI }

WHITESPACE = _{ " " }

ident = @{ (!":" ~ ANY)* }

hostname = { ASCII_ALPHA* }
ip = { 
	ASCII_DIGIT{1,3} ~ "." ~ 
    ASCII_DIGIT{1,3} ~ "." ~
    ASCII_DIGIT{1,3} ~ "." ~
    ASCII_DIGIT{1,3}
}
port = { ASCII_DIGIT{1,5} }

endpoint = { endpoint_protocol ~ (endpoint_host | endpoint_port)* }
endpoint_protocol = { "default" | "tcp" }
endpoint_host = { "-h" ~ (ip | hostname) }
endpoint_port = { "-p" ~ port }

